INSERT INTO quote (id, text, author) VALUES
(1, 'The only way to do great work is to love what you do.', 'Steve Jobs'),
(2, 'Si tu gagnes, tu vis. Si tu perds, tu meurs. Si tu ne te bats pas, tu ne peux pas gagner.', 'Eren Jaeger'),
(3, 'Dans la vie, soit tu es quelqu''un, soit tu n''es personne. Il n''y a pas d''entre-deux.', 'Johnny Silverhand'),
(4, 'Parfois, pour avancer, il faut faire un pas en arrière.', 'V'),
(5, 'Peu importe la distance parcourue, le voyage le plus important est celui que l''on entreprend pour se comprendre soi-même.', 'Cheng Xiaoshi'),
(6, 'Le passé ne peut être changé, mais l''avenir est entre nos mains.', 'Lu Guang'),
(7, 'Même si le monde est cruel, il faut continuer à avancer.', 'Shinei Nouzen'),
(8, 'La seule façon de changer le monde est de se battre pour ce en quoi l''on croit.', 'Vladilena Milizé'),
(9, 'La meilleure façon de prédire l’avenir est de le créer.', 'Peter Drucker'),
(10, 'Le seul moyen de faire un excellent travail est d’aimer ce que vous faites.', 'Steve Jobs'),
(11, 'Croyez en vous et vous êtes à mi-chemin.', 'Theodore Roosevelt'),
(12, 'Votre temps est limité, ne le gaspillez pas à vivre la vie de quelqu’un d’autre.', 'Steve Jobs'),
(13, 'L’avenir appartient à ceux qui croient en la beauté de leurs rêves.', 'Eleanor Roosevelt'),
(14, 'Peu importe la lenteur avec laquelle vous avancez, tant que vous ne vous arrêtez pas.', 'Confucius'),
(15, 'Vous manquez 100 % des tirs que vous ne prenez pas.', 'Wayne Gretzky'),
(16, 'La seule limite à notre réalisation de demain sera nos doutes d’aujourd’hui.', 'Franklin D. Roosevelt'),
(17, 'Ne regardez pas l’horloge ; faites ce qu’elle fait. Continuez.', 'Sam Levenson'),
(18, 'Ce qui est derrière nous et ce qui est devant nous sont de peu d’importance comparé à ce qui est en nous.', 'Ralph Waldo Emerson'),
(19, 'La meilleure vengeance est un succès massif.', 'Frank Sinatra'),
(20, 'Oh oui, le passé peut faire mal. Mais à mon avis, vous pouvez soit en souffrir, soit en tirer des leçons.', 'Rafiki, Le Roi Lion'),
(21, 'La plus grande gloire n’est pas de ne jamais tomber, mais de se relever à chaque fois.', 'Nelson Mandela'),
(22, 'Votre vie ne s’améliore pas par hasard, elle s’améliore par le changement.', 'Jim Rohn'),
(23, 'La seule personne que vous êtes destiné à devenir est celle que vous décidez d’être.', 'Ralph Waldo Emerson'),
(24, 'Allez avec confiance dans la direction de vos rêves. Vivez la vie que vous avez imaginée.', 'Henry David Thoreau'),
(25, 'Quand vous voulez réussir autant que vous voulez respirer, alors vous serez réussi.', 'Eric Thomas'),
(26, 'Le succès n’est pas un accident. C’est du travail acharné, de la persévérance, de l’apprentissage, de l’étude, du sacrifice et surtout, l’amour de ce que vous faites ou apprenez à faire.', 'Pelé'),
(27, 'Ne vous laissez pas abattre par les peurs dans votre esprit. Laissez-vous guider par les rêves dans votre cœur.', 'Roy T. Bennett'),
(28, 'Le pessimiste voit la difficulté dans chaque opportunité. L’optimiste voit l’opportunité dans chaque difficulté.', 'Winston Churchill'),
(29, 'Ne laissez pas hier prendre trop de place aujourd’hui.', 'Will Rogers'),
(30, 'Vous apprenez plus de l’échec que du succès. Ne laissez pas cela vous arrêter. L’échec construit le caractère.', 'Inconnu'),
(31, 'Ce n’est pas une question de perfection. C’est une question d’effort.', 'Jillian Michaels'),
(32, 'Investissez dans vos rêves. Travaillez dur maintenant. Brillez plus tard.', 'Inconnu'),
(33, 'Les limitations n’existent que dans nos esprits. Mais si nous utilisons notre imagination, nos possibilités deviennent illimitées.', 'Jamie Paolinetti'),
(34, 'Ce qui est derrière nous et ce qui est devant nous sont de peu d’importance comparé à ce qui est en nous.', 'Ralph Waldo Emerson'),
(35, 'Le plus grand chêne était autrefois une petite glande qui a tenu bon.', 'Inconnu'),
(36, 'Votre vie est le résultat de vos choix. Si vous n’aimez pas votre vie, il est temps de faire de meilleurs choix.', 'Inconnu'),
(37, 'Faites chaque jour quelque chose qui vous fait peur.', 'Eleanor Roosevelt'),
(38, 'Toute progression se fait en dehors de la zone de confort.', 'Michael John Bobak'),
(39, 'Les personnes qui sont assez folles pour penser qu’elles peuvent changer le monde sont celles qui le font.', 'Rob Siltanen'),
(40, 'Ne laissez pas la peur de perdre être plus grande que l’excitation de gagner.', 'Robert Kiyosaki'),
(41, 'Quelle merveilleuse chose que personne n’ait besoin d’attendre un seul instant avant de commencer à améliorer le monde.', 'Anne Frank'),
(42, 'La seule façon d’accomplir l’impossible est de croire que c’est possible.', 'Charles Kingsleigh'),
(43, 'Agissez comme si ce que vous faites fait une différence. C’est le cas.', 'William James'),
(44, 'Le succès n’est pas définitif, l’échec n’est pas fatal : c’est le courage de continuer qui compte.', 'Winston Churchill'),
(45, 'Le seul endroit où le succès vient avant le travail est dans le dictionnaire.', 'Vidal Sassoon'),
(46, 'N’ayez pas peur de renoncer au bien pour aller vers le grand.', 'John D. Rockefeller'),
(47, 'Votre travail va remplir une grande partie de votre vie, et la seule façon d’être vraiment satisfait est de faire ce que vous croyez être un excellent travail. Et la seule façon de faire un excellent travail est d’aimer ce que vous faites.', 'Steve Jobs'),
(48, 'Ne comptez pas les jours, faites en sorte que les jours comptent.', 'Muhammad Ali'),
(49, 'La seule chose qui se dresse entre vous et votre objectif est l’histoire que vous continuez à vous raconter sur pourquoi vous ne pouvez pas l’atteindre.', 'Jordan Belfort'),
(50, 'Le succès vient généralement à ceux qui sont trop occupés pour le chercher.', 'Henry David Thoreau'),
(51, 'N’ayez pas peur d’échouer. Ayez peur de ne pas essayer.', 'Michael Jordan'),
(52, 'La meilleure façon de commencer est d’arrêter de parler et de commencer à faire.', 'Walt Disney'),
(53, 'Votre vie est votre message au monde. Assurez-vous qu’il soit inspirant.', 'Inconnu'),
(54, 'Vous n’êtes jamais trop petit pour faire une différence.', 'Greta Thunberg'),
(55, 'Plus vous travaillez dur pour quelque chose, plus vous vous sentirez bien lorsque vous l’atteindrez.', 'Inconnu'),
(56, 'Rêvez grand et osez échouer.', 'Norman Vaughan'),
(57, 'Le succès, c’est aller d’échec en échec sans perdre son enthousiasme.', 'Winston Churchill'),
(58, 'Ne laissez pas ce que vous ne pouvez pas faire interférer avec ce que vous pouvez faire.', 'John Wooden'),
(59, 'Le meilleur projet sur lequel vous travaillerez jamais, c’est vous-même.', 'Mel Robbins');
